name: Main CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: tbo-app

jobs:
  # =========================
  # UNIT TESTS
  # =========================
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  # =========================
  # SCA - DEPENDENCIES (OWASP)
  # =========================
  sca-dependencies:
    name: SCA - OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "tbo-app"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
          args: >
            --enableExperimental
            --failOnCVSS 0
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

  # =========================
  # SAST - CODEQL
  # =========================
  sast:
    name: CodeQL
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: tests

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
          queries: security-extended

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v4

      - name: Fail build if CodeQL alerts exist
        run: |
          alerts=$(gh api repos/${{ github.repository }}/code-scanning/alerts \
            --jq '[.[] | select(.state=="open" and .tool.name=="CodeQL")] | length')

          echo "Open CodeQL alerts: $alerts"

          if [ "$alerts" -gt 0 ]; then
            echo "Security vulnerabilities detected by CodeQL"
            exit 1
          else
            echo "No CodeQL vulnerabilities found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # =========================
  # BUILD AND SCAN IMAGE
  # =========================
  build-and-scan:
    name: Build Docker + SCA Trivy + DAST ZAP
    runs-on: ubuntu-latest
    needs: [tests, sca-dependencies, sast]
    # needs: tests
    if: github.event_name == 'push'
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      # ---------- Build Docker image ----------
      - name: Set image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=beta" >> $GITHUB_OUTPUT
          fi
  
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.tag.outputs.tag }} .
  
      # ---------- SCA - Trivy ----------
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM,LOW
          exit-code: 1
  
      # ---------- DAST - OWASP ZAP ----------
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 $IMAGE_NAME:${{ steps.tag.outputs.tag }}
          sleep 20
  
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: http://localhost:5000
          fail_action: true
          allow_issue_writing: false
          artifact_name: zapscan

  
      # ---------- Push image ----------
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} \
            ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:${{ steps.tag.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:${{ steps.tag.outputs.tag }}
